spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/pedido
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
