spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/marketplace
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
