spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/login
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
